name: Debug Konflux CI

on:
  check_run:
    types:
      - completed  # Listen for check completion

jobs:
  debug-konflux:
    runs-on: ubuntu-latest
    if: |
      github.event.check_run.conclusion == 'success' &&
      (
        (github.event.check_run.head_branch != '' && 
         startsWith(github.event.check_run.head_branch, 'test-')) ||
        (github.event.check_run.pull_requests &&
         github.event.check_run.pull_requests[0].head.ref != '' &&
         startsWith(github.event.check_run.pull_requests[0].head.ref, 'test-'))
      )

    steps:
      - name: Debug Event Payload
        run: echo '${{ toJson(github.event) }}'

      - name: Print Entire Check Run Event
        run: echo '${{ toJson(github.event.check_run) }}'

      - name: Print Check Run Name
        run: |
          echo "CI Check Name: '${{ github.event.check_run.name }}'"

      - name: Print Check Conclusion
        run: |
          echo "Check Conclusion: '${{ github.event.check_run.conclusion }}'"

      - name: Print Branch Information
        run: |
          echo "CI ran on head_branch: '${{ github.event.check_run.head_branch }}'"
          if [[ -n "${{ github.event.check_run.pull_requests[0].head.ref }}" ]]; then
            echo "CI ran on PR branch: '${{ github.event.check_run.pull_requests[0].head.ref }}'"
          else
            echo "No pull request associated."
          fi
