name: Debug Check Run

on:
  check_run:
    types:
      - completed  # Trigger when a check run completes

jobs:
  debug-konflux:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Event Payload
        run: echo '${{ toJson(github.event) }}'

      - name: Print Check Run Name
        run: |
          echo "CI Check Name: '${{ github.event.check_run.name }}'"

      - name: Print Check Conclusion
        run: |
          echo "Check Conclusion: '${{ github.event.check_run.conclusion }}'"

      - name: Print Check Run Details
        run: |
          echo "Check Run URL: '${{ github.event.check_run.html_url }}'"
