name: Test Trigger run to verify

on:
  check_run:
    types:
      - completed  # Listen for check completion

jobs:
  debug-konflux:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Event Payload
        run: echo '${{ toJson(github.event) }}'

      - name: Print Check Run Name
        run: |
          echo "CI Check Name: '${{ github.event.check_run.name }}'"

      - name: Print Check Conclusion
        run: |
          echo "Check Conclusion: '${{ github.event.check_run.conclusion }}'"
