name: Trigger on Konflux CI Success

on:
  check_run:
    types:
      - completed  # Listen for check completion

jobs:
  trigger-on-konflux:
    if: |
      github.event.check_run.conclusion == 'success' &&
      startsWith(github.event.check_run.name, 'Konflux Production Internal / rbc-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Script
        run: |
          echo "Konflux CI check '${{ github.event.check_run.name }}' succeeded! Running the script..."
        
