name: Trigger on Konflux CI Success

on:
  check_run:
    types:
      - completed  # Listen for check completion

jobs:
  trigger-on-konflux:
    runs-on: ubuntu-latest
    if: |
      github.event.check_run.conclusion == 'success' &&
      contains(github.event.check_run.name, 'Konflux Production Internal / rbc-')
    steps:
      - name: Debug Event Payload
        run: echo '${{ toJson(github.event) }}'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Script
        run: |
          echo "Konflux CI check '${{ github.event.check_run.name }}' succeeded! Running the script..."
          bash ./tools/snapshot-generator/conr.sh
