name: Trigger conforma run on Konflux CI Success

on:
  check_run:
    types:
      - completed  # Listen for check completion

jobs:
  trigger-on-konflux:
    runs-on: ubuntu-latest
    if: |
      github.event.check_run.conclusion == 'success' &&
      startsWith(github.event.check_run.name, 'Konflux Production Internal / rhoai-fbc-fragment-v') &&
      endsWith(github.event.check_run.name, '-on-schedule')

    steps:
      - name: Debug Event Payload
        run: echo '${{ toJson(github.event) }}'

      - name: Echo CI Check Name
        run: |
          echo "The CI check that succeeded is: '${{ github.event.check_run.name }}'"

      - name: Generate github-app token
        id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.RHOAI_DEVOPS_APP_ID }}
          private_key: ${{ secrets.RHOAI_DEVOPS_APP_PRIVATE_KEY }}

      # Trigger the conforma reporter workflow
      - uses: lasith-kg/dispatch-workflow@v2.0.0
        id: trigger-conforma-workflow
        name: Trigger conforma workflow
        with:
          dispatch-method: workflow_dispatch
          repo: conforma-reporter
          owner: red-hat-data-services
          workflow: main.yaml 
          token: ${{ steps.app-token.outputs.token }}
          workflow-inputs: '{"snapshot_target": "${{ github.ref_name }}"}'
          ref: 'main'
          
